version: '3'
services:
  hub:
    image: selenium/hub:4.10
  chrome:
    image: selenium/node-chrome:4.10
    shm_size: '2g'
    depends_on:
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub    #So here we need to put environment variable as it is required so that chrome container can talk with hub     
    - SE_EVENT_BUS_PUBLISH_PORT=4442   #ALL THIS INFORMATION IS PRESENT ON SELENIUM GRID OFFICIAL PAGE
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true   #this will increase the concurrency of each container
    - SE_NODE_MAX_SESSIONS=4   #this means the concurrency of each chrome container will be 4 now
  firefox:
    image: selenium/node-firefox:4.10
    shm_size: '2g'
    depends_on:
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub    
    - SE_EVENT_BUS_PUBLISH_PORT=4442  #This publish port is used to register the node om this port with the hub
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443 #This subscribe port is used to get the information from the hub
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=4
  vendor-portal:
    image: shaarv70/selenium
    depends_on:
    - chrome
    environment:
    - BROWSER=firefox
    - HUB_HOST=hub
    - THREAD_COUNT=3
    - TEST_SUITE=vendor-portal.xml
    volumes:
    - ./output/vendor-portal:/home/selenium-docker/test-output
  flight-reservation:
      image: shaarv70/selenium
      depends_on:
        - firefox
      environment:
        - BROWSER=chrome
        - HUB_HOST=hub
        - THREAD_COUNT=4
        - TEST_SUITE=flight-reservation.xml
      volumes:
      - ./output/flight-reservation:/home/selenium-docker/test-output
