version: '3'
services:
  vendor-portal:
    image: shaarv70/selenium:latest
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub
    - THREAD_COUNT=1
    - TEST_SUITE=vendor-portal.xml
    deploy:
        replicas: 0
    volumes:
    - ./output/vendor-portal:/home/selenium-docker/test-output
  flight-reservation:
      image: shaarv70/selenium:latest
      environment:
        - BROWSER=firefox
        - HUB_HOST=hub
        - THREAD_COUNT=1
        - TEST_SUITE=flight-reservation.xml
      deploy:
        replicas: 1
      volumes:
      - ./output/flight-reservation:/home/selenium-docker/test-output
